### PR TITLE
Fix compile errors in kobuki_gazebo_plugins with Kinetic and Gazebo7

### PR DESCRIPTION
**Pull request by rohbotics**
Rebase of #45

### CODE REVIEW

**Comment by stonier** [comment]
@rohbotics could you squash these commits into one?

**Comment by rohbotics** [comment]
@stonier Squashed

**Comment by rohbotics** [comment]
@stonier After merging can you run a kinetic release, so that we can release turtlebot_interactions?

**Comment by leokoppel** [comment]
@rohbotics I'm trying this out and the change to CMakeLists.txt breaks if `CMAKE_CXX_FLAGS` is set. Can you make a minor change as in https://github.com/turtlebot/turtlebot_create_desktop/commit/9aec5e09cc32e236800502c3825480b7db6af382 ? It may also be better to use the `CXX_STANDARD` property instead.

**Comment by rohbotics** [comment]
@leokoppel, Fixed. Please try it out now

**Comment by leokoppel** [comment]
@rohbotics Yep it builds.

I'm currently getting a segfault when the .so is loaded, but I'm pretty sure it's just my system (from [Kinetic migration guide](http://wiki.ros.org/kinetic/Migration#Qt4.2BAC8-Qt5_Guidelines): "Code that links against both Qt4 and Qt5, directly or indirectly, will segfault. ")  Still figuring it out (i.e. rebuilding everything) but thought I'd mention it in case anyone had the same issue.

**Comment by rohbotics** [comment]
@stonier re-squashed

**Comment by stonier** [comment]
Thanks! 

```
     _  _(o)_(o)_  _
   ._\`:_ F S M _:' \_,
       / (`---'\ `-.
    ,-`  _)    (_,
```

Any further problems you have, keep sending the PR's. We are not actively using kinetic yet, so relying a bit on users for a while.

**Comment by stonier** [comment]
Working on getting a deb release out now.

**Comment by rohbotics** [comment]
Awesome, Thanks!

**Pull request merged**
