### PR TITLE
fix the wrong behavior with a kobuki model on Gazebo5.

### PR DESCRIPTION
**Pull request by DaikiMaekawa**
https://github.com/yujinrobot/kobuki_desktop/issues/41 I modified to not use SetMaxForce method.

[Review on Reviewable](https://reviewable.io/reviews/yujinrobot/kobuki_desktop/42)

### CODE REVIEW

**Comment by DaikiMaekawa** [comment]
The plugin isn't working on Gazebo5 before, so that this PR is necessary aid for avoiding the wrong behavior with ROS Jade. Can you review this one, and then merge it?

**Comment by DaikiMaekawa** [comment]
@bit-pirate Poke

**Comment by bit-pirate** [comment]
First, thanks for the contribution @DaikiMaekawa !

For Kobuki (and TurtleBot) we only support long-term releases, so no Jade. However, I don't want your contribution to be wasted, so I have created a jade branch. Please rebase this PR against the jade branch.

**Comment by DaikiMaekawa** [comment]
@bit-pirate done. https://github.com/yujinrobot/kobuki_desktop/pull/43

**Pull request closed without merging**
